name: SecureLink
description: A cryptocurrency wallet application with dual-device security using ESP32 and Bluetooth.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  shared_preferences: ^2.5.3
  crypto: ^3.0.6
  bip39: ^1.0.6
  web3dart: ^2.6.1
  qr_flutter: ^4.1.0
  barcode_scan2: ^4.5.1
  http: ^1.5.0
  provider: ^6.1.5+1
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
